<?php include "header.php" ?>

<div class="container">
  <h1>Climate change and companies</h1>

  <img class="companies-header" src="img/companies/Asset 1.png" alt="business and climate change picture">
  <p>Climate change can affect businesses in various ways, including extreme weather (that can prevent employees to commute to work, to work differently, a shortage of raw natural resources, materials), and costs (generated by taxes to slow down climate downfall).</p><br>

  <p>Moreover, agreements and action plans ratified by every country have direct incidences on companies. It is, therefore, their call to make it a strength to take a turn, overcome the challenges and take the opportunity to rethink their strategy, work and be productive in a different way while raising awareness and retaining their customers and employees.</p>

  <h2><i class="fas fa-shopping-basket"></i> Constraints or opportunities ?</h2>

  <p>These agreements have led to new laws and regulations. These rules are different for every country but are affecting everybody, businesses and individuals, such as the "aviation tax" worldwide, "Diesel tax" in Europe or "carbon tax" in the USA. These taxes represent a lot for businesses so making some changes will be an investment and will make any business save money in the long run.</p><br>

  <p>Now, if you are <a href="#employee">working in a firm</a>, it's never too late to talk about climate breakdown and the changes you can implement to your colleagues and supervisor, one at a time, and if you're a <a href="#ceo">business owner,</a> it's time to implement changes to make the most of green opportunities !</p>

  <h2 id="employee"><i class="fas fa-briefcase"></i> Positive changes if you work in a company:</h2>
  <ul class='employers-actions'>

    <li><div>Electricity: </div><br>you have in your office the opportunity to choose to switch on and off the light when you are working and when leaving the office. You can also reduce the heat and AC to a minimum by dressing up accordingly with the weather. You can switch your computer to power saving option and switch off your computer/laptop, screen(s) and printer while leaving the office rather than putting everything into sleep mode.</li><br>
    <img class="employee-picture" src="img/companies/coffee-cup-laptop-265070.jpg" alt="mug and computer image">
    <li><div>Save Co2 while surfing the Web: </div><br>Rather than using Google, you can switch to <a target="_blank" href="https://www.ecosia.org/">Ecosia Search engine</a> that contributes to the CO2 reduction by donating 80% of its benefits to a NGO who plants trees.</li><br>
    <li><div>Paper reduction: </div><br>you can decrease your paper consumption by printing <b>only necessary</b> documents that cannot be seen on your screen, using both sides. You can also save your meetings dates and times using your outlook calendar, or writing notes on a Word spreadsheet instead of a piece of paper? if you really need paper, use recycled paper, which would contribute to reducing deforestation and therefore CO2.</li><br>
    <li><div>Commute: </div><br>See if, instead of taking your car, you can either walk or bike to work (to get some workout done for the day), use public transports (you will have more time to do something else like to read for example) or carpool with a colleague (you can learn to know them better outside of work). </li><br>
    <li><div>Bring your mug: </div><br>Drinking is so important, but reducing plastic cups is as well. Plus, it is healthier to drink in a mug rather than a plastic cup, especially if you drink hot beverages. Think of how many plastic cups you can save a year!</li><br>
    <li><div>Office supplies: </div><br>Encourage your colleagues to order office supplies for everyone at the same time to reduce delivery carbon footprint, or if you have the opportunity, go directly to the store together.</li><br>
    <li><div>Discuss working from home: </div><br>Unfortunately, a lot of employers are still reluctant to make their employees telecommute, from an organizational and trust issue. If this is the case, you can speak about it around you. More employees will discuss it, the more your employer or direct manager will embrace this new idea. If you are free to telecommute, try to implement it at least once a week.</li>
  </ul>

  <h2 id="ceo"><i class="fas fa-user-tie"></i> Positive changes if you own a business:</h2>

  <ul class='employers-actions'>

    <img class="carbon-foot" src="img/companies/reducing-co2-1.png" alt="carbon footprint certification">
    <li><div>Measure your carbon footprint: </div><br> To address changes, you must know what could be better in your business daily activity, from the reception of goods and services from suppliers to the delivery and feedback from customers. To do so, you can either <a href="https://www.sustainablebusinesstoolkit.com/how-to-measure-a-carbon-footprint/"  target="_blank">do it on your own</a> or you can call on some new companies that are specialized into this field and you could own a certification! <a href="https://www.carbontrust.com/home/" target="_blank">Please click here to find out more about it</a>.</li><br>
    <li><div>Run a deep business analysis:  </div><br>Also called a SWOT, (for Strengths, Weaknesses, Opportunities, and Treats), it allows you to visualize your business from both internally and externally, from an employee, supplier, shareholder, and customer perspective. It will put into perspective the challenges and opportunities for your activity regarding climate changes.</li><br>
    <li><div>Audit your supply-chain:  </div><br>To evaluate the impact of your supply chain in terms of cost, speed and quality, and address these risks to implement changes to create positive value and increase its competitivity.</li><br>
    <li><div>Review your suppliers offer:  </div><br>In order to reduce your carbon footprint, you could review your suppliers origin. Maybe some suppliers deliver quality products and service nearby rather than on the other side of the world. You can also pressure your supplier to adopt a set of rules to manage and reduce their carbon footprint.</li><br>

    <div class="google-idea-img">
      <a href="https://www.cnbc.com/2019/03/20/these-public-companies-do-the-most-to-help-prevent-climate-change.html" target="_blank">
        <img class="Google-roof" src="img/companies/105796794-155266.jpeg" alt="solar panel on Google's Headquarters" legend="Solar panels on Google's Headquarters. Steve Proehl, COrbis Documentary :getty images"></a>
        <p><b>Solar panels on Google headquarters in California </b><br>
          <em>Steve Proehl | Corbis Documentary | Getty Image</em></p>
          <hr>
        </div>

        <li><div>Switch your fleet to electric or hybrid:  </div><br>This apply if your company uses business cars or trucks, and especially if the fleet is getting old (therefore more polluting). This is an investment but it will allow you to redeem taxes cost and maybe benefit from governmental or car dealer discounts.</li><br>
        <li><div>Optimize your employees transportation:  </div><br>Encourage your employees to have video conference meetings (Skype, FaceTime, Zoom) instead of flying, support telecommuting by setting up a dedicated IT rules of procedure. Finally, public transportation could be promoted by paying off 50% off their montly transport pass, as it is compulsory in some countries. </li><br>
        <li><div>Reorganize the office furnitures:  </div><br>This includes displaying different waste containers to encourage employees to do selective sorting to recycle their waste, sensibilise employees regarding electricity consumptions and install energy efficient lighting.</li><br>
        <li><div>Reduce heading and AC consumption: </div><br>Try (if possible) reviewing the insulation of the premises, installing double glazing and installing optimal timing control.</li>
      </ul>
    </div>

    
    <img class="business-picture" src="img/companies/camera-coffee-composition-1509428.jpg" alt="business strategy image">

    <?php include "footer.php" ?>
