<?php include "header.php" ?>

<div class="container" id="top">
  <h1>Help about the website</h1>

  <p>Welcome to the Help page to help you navigate through the website. <br>

  Please note that, at any moment, you can click on this button <img class="topbthHelp" src="img/help/top.PNG" alt="top button"> located on the bottom-right of your page, to go back to the top of the page.</p>

  <h3><i class="fas fa-igloo"></i>Homepage</h3>
  <img class="scrollPic" src="img/help/scroll.jpg" alt="scrolling mouse">
<p>First, you probably landed on the homepage, represented by a small igloo ( <i class="fas fa-igloo"></i>). From there you can either scroll down (with your mouse) or click on the white arrow that appears to navigate down the page. <br>

<br>

The 6 polygons represent a page regarding either causes, effects or consequences of climate breakdown. These polygons are buttons and you can, therefore, click on any of them to visit the page.


<img class="big-pic" src="img/help/buttons.PNG" alt="website buttons">

From the homepage, you can also scroll down again and see the map of the carbon footprint by countries. The website where I found the data is (at least now) down, I made a downloadable  ordered list of countries with their emissions per percentage. you can download it by clicking on the link below the legend.</p>

<img class="big-pic" src="img/help/map.PNG" alt="website map link">


<h3><i class="fas fa-thermometer-three-quarters"></i> Causes and consequences</h3>

<p>This page is quite straightforward and list the main reasons of climate breakdown, generated by man. under the "Risks if we don't do anything", I've included a slider. You can go through the pictures with the help of the right and left white arrows on the side of each slide.</p>

<img class="big-pic" src="img/help/slider.PNG" alt="slider">

<h3><i class="fas fa-vote-yea"></i> Governments</h3>

<p>This page lists the main meetings and Summits between organizations and States as well as the discussions, decisions, and conventions signed to generate major changes to limit climate breakdown. Please scroll down to get through the timeline.</p>

<h3><i class="fas fa-calculator"></i> Companies, food and transports</h3>

<p>These pages are quite straightforward, you just have to scroll down to keep reading.</p>

<h3><i class="far fa-lemon"></i> Lifestyle</h3>

<p>For this one, you can grab a bubble with the mouse and drag it anywhere. If you want to read what's hidden behind the picture, click on each bubble to open it.</p>

<img class="big-pic" src="img/help/lifestyle.PNG" alt="lifestyle page">

<h3><i class="fas fa-feather-alt"></i> Quiz</h3>

<p>The quiz has been made to assess where you and your habits are, regarding climate breakdown. To start the quiz, please click on the "Let's Begin" button above the wind turbines picture. Then, click on the button to the left of the sentence that looks the most like your habits and click on "Next". At the end of the 10 questions, click on "submit" and your result will appear.</p>

<h3><i class="fas fa-book"></i> Legal pages</h3>

<p>In the footer, you can see 3 links regarding legal sections:</p>
<br>
<ul>
    <li>This website doesn't have any cookies so the cookies regulation doesn't havee to be mentionned</li>
    <li>The <a href="about.php">About</a> page is to read about why I created this website</li>
    <li>The <a href="terms-and-conditions.php">terms and conditions</a> page list the legal obligations of this website</li>
    <li>The <a href="references.php">References</a> page lists all the websites I used to build this website</li>
</ul>
<br>
<p>If you have any question or remarks regarding this website, please contact me. You can find my email information <a href="mailto:toocamille@gmail.com">here</a> or under the "contact" sections in the Terms and conditions page.</p>

<section class="bottom-cta">

<button class="top" type="button" name="button"><a href="index.php">Go back to the Homepage</a></button>

</section>
</div>
<?php include "header.php" ?>

<style>
/* HELP PAGE */

.topbthHelp{
    max-width: 30px;
}
.scrollPic{
    max-width: 100px;
    float: right;
    margin-left: 1%;
}
.big-pic{
    max-width: 600px;
    display: block;
    margin: 3% auto;
    box-shadow: -webkit-box-shadow: 0px 0px 5px 0px rgba(145,145,145,1);
-moz-box-shadow: 0px 0px 5px 0px rgba(145,145,145,1);
box-shadow: 0px 0px 5px 0px rgba(145,145,145,1);
}


</style>